#budgets
-
  method: get
  route: 'budgets'
  command: Cobudget::Budgets::List
  params:
  description: Returns a list of all budgets

-
  method: get
  route: 'budgets/:budget_id/buckets'
  command: Cobudget::Buckets::ListAvailable
  params: '*budget_id, *state'
  description: Returns budget buckets of defined state

-
  method: get
  route: 'budgets/:budget_id/allocated'
  command: Cobudget::BudgetAllocatedBalanceEnquiry
  params: '*budget_id'
  description: Returns the amount allocated to the given budget

-
  method: get
  route: 'budgets/:budget_id/unallocated'
  command: Cobudget::BudgetUnallocatedBalanceEnquiry
  params: '*budget_id'
  description: Returns the unallocated amount for a given budget

-
  method: get
  route: 'budgets/:budget_id/total'
  command: Cobudget::BudgetTotalEnquiry
  params: '*budget_id'
  description: Returns the total for a given budget

-
  method: get
  route: 'budgets/:budget_id'
  command: Cobudget::Budgets::Show
  params: '*budget_id'

-
  method: put
  route: 'budgets/:budget_id'
  command: Cobudget::Budgets::Update
  params: '*user_id, *budget_id, name, description'

-
  method: post
  route: 'budgets'
  command: Cobudget::Budgets::Create
  params: '*name, description'
  description: Creates a budget

#buckets
-
  method: delete
  route: 'budgets/:budget_id/buckets/:bucket_id'
  command: Cobudget::Buckets::Delete
  params: '*user_id, *bucket_id, *budget_id'
  description: Deletes a bucket from budget

-
  method: get
  route: 'buckets/:bucket_id'
  command: Cobudget::Buckets::Show
  params: '*bucket_id'
  description: Returns a specific bucket

-
  method: get
  route: 'buckets/:bucket_id/balance'
  command: Cobudget::BucketBalanceEnquiry
  params: '*bucket_id'
  description: Returns the balance for a specific bucket

-
  method: put
  route: 'buckets/:bucket_id'
  command: Cobudget::Buckets::Update
  params: '*user_id, *bucket_id, *budget_id, name, description, sponsor_id, minimum, maximum'
  description: Update a bucket

-
  method: post
  route: 'buckets'
  command: Cobudget::Buckets::Create
  params: '*user_id, *budget_id, *name, *description, minimum, maximum, sponsor_id'
  description: Creates a bucket

-
  method: post
  route: 'buckets/:bucket_id/set-state'
  command: Cobudget::Buckets::SetState
  params: '*bucket_id, state'
  description: Sets the state of a bucket.

-
  method: delete
  route: 'buckets/:bucket_id'
  command: Cobudget::Buckets::Delete
  params: '*user_id, *bucket_id'
  description: Deletes a bucket

#bucket comments
-
  method: get
  route: 'buckets/:bucket_id/comments'
  command: Cobudget::Comments::ListByBucket
  params: '*bucket_id'
  description: gets comments for a bucket

-
  method: post
  route: 'buckets/:bucket_id/comments'
  command: Cobudget::Comments::Create
  params: '*bucket_id, #current_user, body, comment(parent)'
  description: creates a comment for a bucket

-
  method: delete
  route: 'buckets/:bucket_id/comments/:comment_id'
  command: Cobudget::Comments::Delete
  params: '*bucket_id, comment_id'
  description: deletes a comment for a bucket

#users
#-
#  method: get
#  route: 'users/:user_id/budget_account/:budget_id'
#  command: show_accounts
#  params: '*user_id, *budget_id'
#  description: Returns user accounts per budget
#-
  method: get
  route: 'users'
  command: Cobudget::Users::List
  params: ''
  description: Returns all users
-
  method: post
  route: 'users/authenticate'
  command: Cobudget::Users::Authenticate
  params: '*email'
  description: Creates or finds a user by email
-
  method: get
  route: 'users/:user_id'
  command: Cobudget::Users::Show
  params: '*user_id'
  description: Returns a user
#-
#  method: get
#  route: 'users/:user_id/allocatable_by_budget/:budget_id'
#  command: get_allocation_rights
#  params: '*user_id, *budget_id'
#  description: Returns user allocation rights per budget
-
  method: post
  route: 'users'
  command: Cobudget::Users::Create
  params: '*name, *email, #bg_color, #fg_color'
  description: Create a user
#-
#  method: post
#  route: 'users/:user_id/grant_allocation_rights/:budget_id'
#  command: grant_allocation_rights
#  params: '*user_id, *budget_id, *amount'
#  description: Creates user allocatable for a budget
-
  method: put
  route: 'users/:user_id'
  command: Cobudget::Users::Update
  params: '*name, *email, bg_color, fg_color'
  description: Update a user


#accounts
-
  method: get
  route: 'budgets/:budget_id/accounts'
  command: Cobudget::Accounts::ListByBudget
  params:  '*budget_id'
  description: Returns a list of all accounts for a budget

-
  method: get
  route: 'accounts/:account_id'
  command: Cobudget::Accounts::Show
  params: '*account_id'
  description: Get single account by id
-
  method: post
  route: 'accounts/:account_id/transfer'
  command: Cobudget::Accounts::TransferFunds
  params: '*account_id(from account), to_account_id, amount_dollars'
  description: Transfer funds from one account to another.
-
  method: post
  route: 'accounts'
  command: Cobudget::Accounts::Create
  params: '*user_id, *budget_id'
  description: Admin creates an account for a given user and a budget

#allocations
#-
#  method: post
#  route: 'allocations'
#  command: create_allocations
#  params: '*user_id, *bucket_id, *amount'
#  description: Create an allocation for a bucket
#-
#  method: patch
#  route: 'allocations/:allocation_id'
#  command: update_allocations
#  params: '*allocation_id, *bucket_id, *budget_id, name, description, sponsor_id, minimum, maximum'
#  description: Update an allocation
