#budgets
-
  get:
    route: 'budgets'
    command: list_budgets
    params: 
    description: Returns a list of all budgets

-
  get:
    route: 'budgets/:budget_id/buckets'
    command: list_available_buckets
    params: '*budget_id'
    description: Returns a specific budget

-
  get:
    route: 'budgets/:budget_id/allocated'
    command: budget_allocated_balance_enquiry
    params: '*budget_id'
    description: Returns the amount allocated to the given budget

-
  get:
    route: 'budgets/:budget_id/unallocated'
    command: budget_allocated_balance_enquiry
    params: '*budget_id'
    description: Returns the unallocated amount for a given budget

-
  get:
    route: 'budgets/:budget_id/total'
    command: budget_total_enquiry
    params: '*budget_id'
    description: Returns the total for a given budget

-
  put:
    route: 'budgets/:budget_id'
    command: update_buckets
    params: '*user_id, *budget_id, name, description'

-
  post:
    route: 'budgets'
    command: create_budgets
    params: '*name, description'
    description: Creates a budget

-
  delete:
    route: 'budgets/:budget_id/buckets/:bucket_id'
    command: delete_buckets
    params: '*user_id, *bucket_id, *budget_id'
    description: Deletes a bucket from budget

#buckets
-
  get:
    route: 'buckets/:bucket_id'
    command: show_buckets
    params: '*bucket_id'
    description: Returns a specific bucket

-
  get:
    route: 'buckets/:bucket_id/balance'
    command: bucket_balance_enquiry
    params: '*bucket_id'
    description: Returns the balance for a specific bucket

-
  get:
    route: 'buckets/:bucket_id/allocations'
    command: list_by_bucket_allocations
    params: '*bucket_id'
    description: Returns a list of allocations by bucket

-
  put:
    route: 'buckets/:bucket_id'
    command: update_buckets
    params: '*user_id, *bucket_id, *budget_id, name, description, sponsor_id, minimum, maximum'
    description: Update a bucket

-
  post:
    route: 'buckets'
    command: create_buckets
    params: '*user_id, *budget_id, *name, *description, minimum, maximum, sponsor_id'
    description: Creates a bucket

-
  delete:
    route: 'buckets/:bucket_id'
    command: delete_buckets
    params: '*user_id, *bucket_id'
    description: Deletes a bucket

#users
-
  get:
    route: 'users/:user_id/budget_account/:budget_id'
    command: show_accounts
    params: '*user_id, *admin_id, *budget_id'
    description: Returns user accounts per budget
-
  get:
    route: 'users'
    command: list_users
    params: ''
    description: Returns all users
-
  post:
    route: 'users/authenticate'
    command: authenticate_users
    params: '*email'
    description: Creates or finds a user by email
-
  get:
    route: 'users/:user_id'
    command: show_users
    params: '*user_id'
    description: Returns a user
-
  get:
    route: 'users/:user_id/allocatable_by_budget/:budget_id'
    command: get_allocation_rights
    params: '*user_id, *budget_id'
    description: Returns user allocation rights per budget
-
  post:
    route: 'users'
    command: create_users
    params: '*name, *email, #bg_color, #fg_color'
    description: Create a user 

-
  post:
    route: 'users/:user_id/grant_allocation_rights/:budget_id'
    command: grant_allocation_rights
    params: '*admin_id, *user_id, *budget_id, *amount'
    description: Creates user allocatable for a budget
-
  put:
    route: 'users/:user_id'
    command: update_users
    params: '*name, *email, bg_color, fg_color'
    description: Update a user 
-
  patch:
    route: 'users/:user_id'
    command: update_users
    params: '*name, *email, bg_color, fg_color'
    description: Update a user 


#accounts
-
  get:
    route: 'budgets/:budget_id/accounts'
    command: list_by_budget_accounts
    params:  '*budget_id'
    description: Returns a list of all accounts for a budget

-
  get:
    route: 'accounts/:account_id'
    command: show_accounts
    params: '*account_id'
    description: Get single account by id

-
  post:
    route: 'accounts'
    command: create_accounts
    params: '*user_id, *admin_id, *budget_id'
    description: Admin creates an account for a given user and a budget 

#allocations
-
  post:
    route: 'allocations'
    command: create_allocations
    params: '*user_id, *bucket_id, *amount'
    description: Create an allocation for a bucket
-
  patch:
    route: 'allocations/:allocation_id'
    command: update_allocations
    params: '*allocation_id, *bucket_id, *budget_id, name, description, sponsor_id, minimum, maximum'
    description: Update an allocation
